CREATE TABLE FILIERE(
   id_filiere INT,
   nom VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_filiere),
   UNIQUE(nom)
);

CREATE TABLE CURSUS(
   ID_CURSUS INT,
   NOM VARCHAR(50) NOT NULL,
   id_filiere INT NOT NULL,
   PRIMARY KEY(ID_CURSUS),
   UNIQUE(NOM),
   FOREIGN KEY(id_filiere) REFERENCES FILIERE(id_filiere)
);

CREATE TABLE COURS(
   ID_COURS INT,
   NOM VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_COURS),
   UNIQUE(NOM)
);

CREATE TABLE PROMOTION(
   ID_PROMOTION INT,
   NOM VARCHAR(50) NOT NULL,
   DATE_DEBUT DATE NOT NULL,
   DATE_FIN DATE NOT NULL,
   STATUT_PROMOTION VARCHAR(50) NOT NULL,
   ID_CURSUS INT NOT NULL,
   PRIMARY KEY(ID_PROMOTION),
   UNIQUE(NOM),
   FOREIGN KEY(ID_CURSUS) REFERENCES CURSUS(ID_CURSUS)
);

CREATE TABLE COURS_PLANIFIE(
   ID_COURS_PLANIFIE INT,
   ID_COURS INT NOT NULL,
   ID_PROMOTION INT NOT NULL,
   PRIMARY KEY(ID_COURS_PLANIFIE),
   UNIQUE(ID_PROMOTION, ID_COURS),
   FOREIGN KEY(ID_COURS) REFERENCES COURS(ID_COURS),
   FOREIGN KEY(ID_PROMOTION) REFERENCES PROMOTION(ID_PROMOTION)
);

CREATE TABLE UTILISATEUR(
   ID_UTILISATEUR INT,
   NOM VARCHAR(50) NOT NULL,
   PRENOM VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   MOT_DE_PASSE_HACHE VARCHAR(255) NOT NULL,
   ACTIF BOOLEAN NOT NULL,
   PRIMARY KEY(ID_UTILISATEUR),
   UNIQUE(EMAIL)
);

CREATE TABLE ELEVE(
   ID_UTILISATEUR INT,
   DATE_NAISSANCE DATE NOT NULL,
   PRIMARY KEY(ID_UTILISATEUR),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE FORMATEUR(
   ID_UTILISATEUR INT,
   PRIMARY KEY(ID_UTILISATEUR),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE REFERENTE_ADMIN(
   ID_UTILISATEUR INT,
   PRIMARY KEY(ID_UTILISATEUR),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE ADMINISTRATEUR(
   ID_UTILISATEUR INT,
   PRIMARY KEY(ID_UTILISATEUR),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE INSCRIPTION(
   ID_INSCRIPTION INT,
   DATE_INSCRIPTION DATETIME NOT NULL,
   STATUT_INSCRIPTION VARCHAR(50) NOT NULL,
   DATE_ANNULATION DATETIME,
   MOTIF_ANNULATION VARCHAR(500),
   FORCEE BOOLEAN NOT NULL,
   JUSTIFICATION_FORCAGE VARCHAR(500),
   ID_UTILISATEUR_REFERENTE_ANNULATION INT,
   ID_UTILISATEUR_REFERENTE_CREATION INT NOT NULL,
   ID_UTILISATEUR_ELEVE INT NOT NULL,
   PRIMARY KEY(ID_INSCRIPTION),
   FOREIGN KEY(ID_UTILISATEUR_REFERENTE_ANNULATION) REFERENCES REFERENTE_ADMIN(ID_UTILISATEUR),
   FOREIGN KEY(ID_UTILISATEUR_REFERENTE_CREATION) REFERENCES REFERENTE_ADMIN(ID_UTILISATEUR),
   FOREIGN KEY(ID_UTILISATEUR_ELEVE) REFERENCES ELEVE(ID_UTILISATEUR)
);

CREATE TABLE INSCRIPTION_PROMOTION(
   ID_INSCRIPTION INT,
   ID_PROMOTION INT NOT NULL,
   PRIMARY KEY(ID_INSCRIPTION),
   FOREIGN KEY(ID_INSCRIPTION) REFERENCES INSCRIPTION(ID_INSCRIPTION),
   FOREIGN KEY(ID_PROMOTION) REFERENCES PROMOTION(ID_PROMOTION)
);

CREATE TABLE INSCRIPTION_COURS(
   ID_INSCRIPTION INT,
   ID_COURS_PLANIFIE INT NOT NULL,
   PRIMARY KEY(ID_INSCRIPTION),
   FOREIGN KEY(ID_INSCRIPTION) REFERENCES INSCRIPTION(ID_INSCRIPTION),
   FOREIGN KEY(ID_COURS_PLANIFIE) REFERENCES COURS_PLANIFIE(ID_COURS_PLANIFIE)
);

CREATE TABLE SEANCE(
   ID_SEANCE INT,
   DATE_HEURE_DEBUT DATETIME NOT NULL,
   DATE_HEURE_FIN DATETIME NOT NULL,
   ID_UTILISATEUR_FORMATEUR INT,
   ID_COURS_PLANIFIE INT NOT NULL,
   PRIMARY KEY(ID_SEANCE),
   FOREIGN KEY(ID_UTILISATEUR_FORMATEUR) REFERENCES FORMATEUR(ID_UTILISATEUR),
   FOREIGN KEY(ID_COURS_PLANIFIE) REFERENCES COURS_PLANIFIE(ID_COURS_PLANIFIE)
);

CREATE TABLE COMPOSER(
   ID_CURSUS INT,
   ID_COURS INT,
   RANG INT NOT NULL,
   PRIMARY KEY(ID_CURSUS, ID_COURS),
   UNIQUE(ID_CURSUS, RANG),
   FOREIGN KEY(ID_CURSUS) REFERENCES CURSUS(ID_CURSUS),
   FOREIGN KEY(ID_COURS) REFERENCES COURS(ID_COURS)
);
