spring.application.name=formagest

#Connexion à la base de données
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/formagest}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:formagest}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#Détail des requêtes pour le développement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

#Fixtures (data.sql) :
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#JWT
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=3600000
