CREATE TABLE COURSE
(
    COURSE_ID INT,
    NAME      VARCHAR(50) NOT NULL,
    PRIMARY KEY (COURSE_ID),
    UNIQUE (NAME)
);

CREATE TABLE APP_USER
(
    ID_USER   INT,
    LASTNAME  VARCHAR(50)  NOT NULL,
    FIRSTNAME VARCHAR(50)  NOT NULL,
    EMAIL     VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL,
    ACTIVE    BOOLEAN      NOT NULL,
    ROLE      VARCHAR(50)  NOT NULL,
    PRIMARY KEY (ID_USER),
    UNIQUE (EMAIL)
);

CREATE TABLE STUDENT
(
    ID_USER    INT,
    BIRTH_DATE DATE NOT NULL,
    PRIMARY KEY (ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES APP_USER (ID_USER)
);

CREATE TABLE TEACHER
(
    ID_USER INT,
    PRIMARY KEY (ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES APP_USER (ID_USER)
);

CREATE TABLE ADMINISTRATIVE_MANAGER
(
    ID_USER INT,
    PRIMARY KEY (ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES APP_USER (ID_USER)
);

CREATE TABLE ADMINISTRATOR
(
    ID_USER INT,
    PRIMARY KEY (ID_USER),
    FOREIGN KEY (ID_USER) REFERENCES APP_USER (ID_USER)
);

CREATE TABLE ENROLLMENT
(
    ENROLLMENT_ID        INT,
    ENROLLMENT_DATE      DATETIME    NOT NULL,
    ENROLLMENT_STATUS    VARCHAR(50) NOT NULL,
    CANCELLED_DATE       DATETIME,
    CANCELLED_REASON     VARCHAR(200),
    ID_USER_CANCELLED_BY INT,
    ID_USER_CREATED_BY   INT         NOT NULL,
    ID_USER_STUDENT      INT         NOT NULL,
    PRIMARY KEY (ENROLLMENT_ID),
    FOREIGN KEY (ID_USER_CANCELLED_BY) REFERENCES ADMINISTRATIVE_MANAGER (ID_USER),
    FOREIGN KEY (ID_USER_CREATED_BY) REFERENCES ADMINISTRATIVE_MANAGER (ID_USER),
    FOREIGN KEY (ID_USER_STUDENT) REFERENCES STUDENT (ID_USER)
);

CREATE TABLE SECTOR
(
    SECTOR_ID INT,
    NAME      VARCHAR(50) NOT NULL,
    ID_USER   INT         NOT NULL,
    PRIMARY KEY (SECTOR_ID),
    UNIQUE (NAME),
    FOREIGN KEY (ID_USER) REFERENCES TEACHER (ID_USER)
);

CREATE TABLE TRACK
(
    TRACK_ID  INT,
    NAME      VARCHAR(50) NOT NULL,
    SECTOR_ID INT         NOT NULL,
    PRIMARY KEY (TRACK_ID),
    UNIQUE (NAME),
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTOR (SECTOR_ID)
);

CREATE TABLE COHORT
(
    COHORT_ID  INT,
    NAME       VARCHAR(50) NOT NULL,
    START_DATE DATE        NOT NULL,
    END_DATE   DATE        NOT NULL,
    STATUS     VARCHAR(50) NOT NULL,
    TRACK_ID   INT         NOT NULL,
    PRIMARY KEY (COHORT_ID),
    UNIQUE (NAME),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACK (TRACK_ID)
);

CREATE TABLE SCHEDULED_COURSE
(
    SCHEDULED_COURSE_ID INT,
    ID_USER_FORMATEUR   INT NOT NULL,
    COURSE_ID           INT NOT NULL,
    COHORT_ID           INT NOT NULL,
    PRIMARY KEY (SCHEDULED_COURSE_ID),
    UNIQUE (COHORT_ID, COURSE_ID),
    FOREIGN KEY (ID_USER_FORMATEUR) REFERENCES TEACHER (ID_USER),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID),
    FOREIGN KEY (COHORT_ID) REFERENCES COHORT (COHORT_ID)
);

CREATE TABLE COHORT_ENROLLMENT
(
    ENROLLMENT_ID INT,
    COHORT_ID     INT NOT NULL,
    PRIMARY KEY (ENROLLMENT_ID),
    FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENT (ENROLLMENT_ID),
    FOREIGN KEY (COHORT_ID) REFERENCES COHORT (COHORT_ID)
);

CREATE TABLE SCHEDULED_COURSE_ENROLLMENT
(
    ENROLLMENT_ID        INT,
    FORCED               BOOLEAN,
    JUSTIFICATION_FORCED VARCHAR(250),
    SCHEDULED_COURSE_ID  INT NOT NULL,
    PRIMARY KEY (ENROLLMENT_ID),
    FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENT (ENROLLMENT_ID),
    FOREIGN KEY (SCHEDULED_COURSE_ID) REFERENCES SCHEDULED_COURSE (SCHEDULED_COURSE_ID)
);

CREATE TABLE COMPOSER
(
    TRACK_ID    INT,
    COURSE_ID   INT,
    STEP_NUMBER INT NOT NULL,
    PRIMARY KEY (TRACK_ID, COURSE_ID),
    UNIQUE (TRACK_ID, STEP_NUMBER),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACK (TRACK_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);
